sudo: false
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: lSpCNSdewRN2fQQ24hE0vXOvRTxrcTkIJrqsrtywrWXJS7BTnmOxZWS8xOd68SrANKRuAQiWpxs5ZESxLQRXaY/R98olDu7XFFLVHmS707HyECyB6PNtUz4cZ1/eIuuMZwhofoctveIh3xuwx07dPxWT67bochCd3S749tu5gU9iUkCc340MqOl/gsh42HMU2SSFLtsulrxI86hYxi0mPpLzW3KrK+AXVar0Bl1CV9S/h3PyFVP9dKWLWl8ki366x4yTp/7UpFBQX7Uce2+G/2BeVFlbbZSFV6//1vmDI8UdYDTEJ1MzuG8MRQOOvW53k5Qn5lcsgJWR4XRNeRiow/0emKo8fMoxYkBWTAypa5P6JGSqgwV/ce2QrMeYtpGaAXrw5lVTu6W/smuX2FVUNfeQnWF7ewEBAw8rjsBjNezBJT8ONJqJTGUcT5df1vYQIFT/OxHt3pL+svZs6JREdUWk2d4a9kwqd2xnCk2vh7YNKXTA5PUiOIl+O2huxhhWz+gzAFQsMr1P+DoXEaUrxtadP8c/HCy3wY+s4FCNhoLVfykjW4xLO+6b4HK2DuZR2Ut9xclcwhOxxOBDOjyQcyOSi34kr0XvWN55wl/7X/zs3jGPZsZy+RQ55ERGpzU/8mCzBccNjBcwu0qrQAe9fe1h9COuXFXVKq1KXiWF7Zw=
  - secure: UbIb/tz9fiUfaHIEMCa8lHU9N2doJYnPtjxXPy/UwcuS6NUeCppVhcxwHSbmtc8mBXWq8qNov16med+Gu8IVSbbPFe3vNzinLXCegmJfndF8YVu4Z0CnshZxOl/cgG1sHBUKfnm4hcgGU0V5fEGum2TiZqWxQ+0v7Jzk9ad8aquMBXJ0Vj+eJfLZF6UomHYtx+CN/m4sSJwOwNWF7DrpDwMS7blyIl25/xdWSdC1U267bdHM0Z6svNey+mwjezQpbx+zirtnzg2G0qlcVd8P8cNcS3WoQNiZfZKaFxhiEsMPBzyrWAL2lCa30DxxXQ92qUjFvoGqCRrbsQq6GliNS8SJuq2/2E6kjh5KtrkxBeAjZSyeU6a/IIl+ddSz2cCmkEtVqHtcxO0beTI18MrdN5XhGPQflM8HJpZTWrRD4oHzlmnZkkxC3pUQZIZKZvv2aeq9j3U/dqqam74svw0b1iMZh6E3Jr4ZQTi8O0IZwCOAOoDz0+nN1nsTD2eZ+hG6wKqLrZBCYX9zXMnsIPnjWsqcC/2ZM7LdZo2wHidJxHG3VPaG1p46GK+BAISN1CGsR/+0HnRebWDTKZ8xyKXDSqa+QteEUOjQIh6on8aEb9uHRHBXS7glsZ15uNlxRcS47NAEWIhhfYiyhotsPQze5Cr0TuTuLgYJw5yDXCS54xw=
